# Create the project structure
mkdir -p coupon-app/static/qr_codes
mkdir -p coupon-app/templates

# Navigate into the project folder
cd coupon-app

# Create empty files
touch app.py
touch coupons.db            # This will be auto-generated by Flask, but you can create an empty placeholder
touch requirements.txt
touch README.md
touch templates/index.html
touch templates/redeem.html

# Done
echo "✅ Folder structure and files created successfully!"
R

